# Generated by Django 5.1.3 on 2024-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0005_rename_variant_color_variant_variant_categery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='products.variant'),
        ),
    ]
