# Generated by Django 5.1.3 on 2024-11-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_color', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('variant_size', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
