# Generated by Django 5.1.3 on 2024-11-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_variant_size_variant_variant_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='variant_color',
            new_name='variant_categery',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='quantity',
        ),
    ]
